# Generated by Django 4.2 on 2024-06-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="message_respond_to",
            field=models.IntegerField(default=0),
        ),
    ]
