# Generated by Django 4.2 on 2024-06-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_reactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AngryReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualtrics_id", models.CharField(max_length=255)),
                ("message_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HeartReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualtrics_id", models.CharField(max_length=255)),
                ("message_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LikeReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualtrics_id", models.CharField(max_length=255)),
                ("message_id", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Reactions",
        ),
    ]
