# Generated by Django 4.2 on 2024-07-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_nicks_is_manipulation_positive"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualtrics_id", models.CharField(max_length=255)),
                ("hesitation", models.IntegerField()),
                ("mouse_movement_seconds", models.IntegerField()),
                ("scroll_seconds", models.IntegerField()),
                ("input_seconds", models.IntegerField()),
            ],
        ),
    ]
