# Generated by Django 4.2 on 2024-07-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_interactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="typing_time",
            field=models.IntegerField(default=0),
        ),
    ]
