# Generated by Django 4.2 on 2024-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_messages_typing_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="prev_message",
            field=models.CharField(default="DEFAULT", max_length=2550),
        ),
        migrations.AddField(
            model_name="messages",
            name="prev_prev_message",
            field=models.CharField(default="DEFAULT", max_length=2550),
        ),
    ]
