# Generated by Django 4.2 on 2024-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_messages_prev_message_messages_prev_prev_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactions",
            name="is_chatroom_finished",
            field=models.IntegerField(default=0),
        ),
    ]
