# Generated by Django 4.2 on 2024-07-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_interactions_is_chatroom_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="bot_response",
            field=models.CharField(default="DEFAULT", max_length=2550),
        ),
    ]
